/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author teyfi
 */
public class GirisEkrani extends javax.swing.JFrame {

    private Islemler islemler = new Islemler();

    /**
     * Creates new form GirisEkrani
     */
    public GirisEkrani() {

        initComponents();
        this.setResizable(false);
        this.setSize(500, 500);
        giris_paneli.setSize(500, 500);
        giris_paneli.setFocusable(true);

        admin_giris_paneli.setFocusable(false);
        admin_giris_paneli.setVisible(false);
        admin_giris_paneli.setSize(500, 500);

        kullanici_giris_paneli.setFocusable(false);
        kullanici_giris_paneli.setVisible(false);
        kullanici_giris_paneli.setSize(500, 500);

        panel_kayit.setFocusable(false);
        panel_kayit.setVisible(false);
        panel_kayit.setSize(500, 500);

        kayit_ad.setText("");
        kayit_email.setText("");
        kayit_ulke.setText("");
        kayit_sifre.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        giris_paneli = new javax.swing.JPanel();
        uye_ol = new javax.swing.JButton();
        admin_girisi = new javax.swing.JButton();
        kullanıcı_girisi = new javax.swing.JButton();
        admin_giris_paneli = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        admin_giris_yap = new javax.swing.JButton();
        admin_giris_yap_mesaj = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        kullanici_giris_paneli = new javax.swing.JPanel();
        kullanici_giris_yap = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kullanici_giris_mesaj = new javax.swing.JLabel();
        kullanici_adi = new javax.swing.JTextField();
        sifre = new javax.swing.JPasswordField();
        panel_kayit = new javax.swing.JPanel();
        kayit_ad = new javax.swing.JTextField();
        kayit_email = new javax.swing.JTextField();
        kayit_sifre = new javax.swing.JTextField();
        kayit_ulke = new javax.swing.JTextField();
        kayit_normal = new javax.swing.JButton();
        kayit_pre = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kayit_mesaj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        giris_paneli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uye_ol.setText("ÜYE OL");
        uye_ol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uye_olActionPerformed(evt);
            }
        });
        giris_paneli.add(uye_ol, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 185, 75));

        admin_girisi.setText("ADMİN GİRİŞİ");
        admin_girisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_girisiActionPerformed(evt);
            }
        });
        giris_paneli.add(admin_girisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 185, 81));

        kullanıcı_girisi.setText("KULLANICI GİRİŞİ");
        kullanıcı_girisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanıcı_girisiActionPerformed(evt);
            }
        });
        giris_paneli.add(kullanıcı_girisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 185, 78));

        jLabel1.setText("username : ");

        jLabel2.setText("Password : ");

        admin_giris_yap.setText("Giris YAP");
        admin_giris_yap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_giris_yapActionPerformed(evt);
            }
        });

        admin_giris_yap_mesaj.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout admin_giris_paneliLayout = new javax.swing.GroupLayout(admin_giris_paneli);
        admin_giris_paneli.setLayout(admin_giris_paneliLayout);
        admin_giris_paneliLayout.setHorizontalGroup(
            admin_giris_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_giris_paneliLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(admin_giris_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(admin_giris_paneliLayout.createSequentialGroup()
                        .addGroup(admin_giris_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(55, 55, 55)
                        .addGroup(admin_giris_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username)
                            .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))
                    .addComponent(admin_giris_yap_mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin_giris_paneliLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(admin_giris_yap, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        admin_giris_paneliLayout.setVerticalGroup(
            admin_giris_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_giris_paneliLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(admin_giris_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(admin_giris_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(admin_giris_yap_mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(admin_giris_yap, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        kullanici_giris_yap.setText("Giris Yap");
        kullanici_giris_yap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanici_giris_yapActionPerformed(evt);
            }
        });

        jLabel3.setText("E mail : ");

        jLabel4.setText("Parola : ");

        kullanici_giris_mesaj.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout kullanici_giris_paneliLayout = new javax.swing.GroupLayout(kullanici_giris_paneli);
        kullanici_giris_paneli.setLayout(kullanici_giris_paneliLayout);
        kullanici_giris_paneliLayout.setHorizontalGroup(
            kullanici_giris_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullanici_giris_paneliLayout.createSequentialGroup()
                .addGroup(kullanici_giris_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kullanici_giris_paneliLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(kullanici_giris_yap, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kullanici_giris_paneliLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(kullanici_giris_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kullanici_giris_mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kullanici_giris_paneliLayout.createSequentialGroup()
                                .addGroup(kullanici_giris_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(76, 76, 76)
                                .addGroup(kullanici_giris_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sifre)
                                    .addComponent(kullanici_adi, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        kullanici_giris_paneliLayout.setVerticalGroup(
            kullanici_giris_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kullanici_giris_paneliLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(kullanici_giris_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kullanici_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(kullanici_giris_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(kullanici_giris_mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(kullanici_giris_yap, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        panel_kayit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_kayit.add(kayit_ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 190, 30));
        panel_kayit.add(kayit_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 190, 30));
        panel_kayit.add(kayit_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 190, 30));
        panel_kayit.add(kayit_ulke, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 180, 40));

        kayit_normal.setText("Normal");
        kayit_normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayit_normalActionPerformed(evt);
            }
        });
        panel_kayit.add(kayit_normal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 120, 60));

        kayit_pre.setText("Preminum");
        kayit_pre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayit_preActionPerformed(evt);
            }
        });
        panel_kayit.add(kayit_pre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 104, 57));

        jLabel5.setText("AD :");
        panel_kayit.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel6.setText("Email :");
        panel_kayit.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel7.setText("Sifre :");
        panel_kayit.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel8.setText("Ülke : ");
        panel_kayit.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        kayit_mesaj.setForeground(new java.awt.Color(255, 51, 102));
        panel_kayit.add(kayit_mesaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 250, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(giris_paneli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(admin_giris_paneli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(190, Short.MAX_VALUE)
                    .addComponent(kullanici_giris_paneli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_kayit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(giris_paneli, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(admin_giris_paneli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 200, Short.MAX_VALUE)
                    .addComponent(kullanici_giris_paneli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_kayit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admin_girisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_girisiActionPerformed
        giris_paneli.setVisible(false);
        giris_paneli.setFocusable(false);

        admin_giris_paneli.setVisible(true);
        admin_giris_paneli.setFocusable(true);


    }//GEN-LAST:event_admin_girisiActionPerformed

    private void uye_olActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uye_olActionPerformed
        giris_paneli.setVisible(false);
        giris_paneli.setFocusable(false);

        panel_kayit.setVisible(true);
        panel_kayit.setFocusable(true);
    }//GEN-LAST:event_uye_olActionPerformed

    private void kullanıcı_girisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanıcı_girisiActionPerformed
        giris_paneli.setVisible(false);
        giris_paneli.setFocusable(false);

        kullanici_giris_paneli.setVisible(true);
        kullanici_giris_paneli.setFocusable(true);
    }//GEN-LAST:event_kullanıcı_girisiActionPerformed

    private void admin_giris_yapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_giris_yapActionPerformed
        admin_giris_yap_mesaj.setText("");
        String ad = username.getText();
        String parola = new String(password.getPassword());
        boolean girdimi = islemler.adminGirisYap(ad, parola);
        if (girdimi == true) {
            Arayuz arayuz = new Arayuz(ad, parola);
            this.setVisible(false);
            this.setFocusable(false);

            arayuz.setVisible(true);
            arayuz.setFocusable(true);

        } else {
            admin_giris_yap_mesaj.setText("giris basarisiz Tekrar Deneyin....");
        }

    }//GEN-LAST:event_admin_giris_yapActionPerformed

    public void kayitBilgiAl(String abonelik_tur) {
        String ad = kayit_ad.getText();
        String email = kayit_email.getText();
        String sifre = kayit_sifre.getText();
        String ulke = kayit_ulke.getText();
        if (ad.isEmpty() != true && email.isEmpty() != true && sifre.isEmpty() != true && ulke.isEmpty() != true) {
            String mesaj = islemler.kayitKullanici(ad, email, sifre, abonelik_tur, ulke);
            if (mesaj.equals("Kullanici Başarıyla Eklenmiştir...")) {
                panel_kayit.setFocusable(false);
                panel_kayit.setVisible(false);
                
                kullanici_giris_paneli.setVisible(true);
                kullanici_giris_paneli.setFocusable(true);
                kullanici_giris_mesaj.setText("");
                kullanici_giris_mesaj.setText(mesaj);
            } else {
                kayit_mesaj.setText("");
                kayit_mesaj.setText(mesaj);
            }
        } else {
            kayit_mesaj.setText("");
            kayit_mesaj.setText("Girilen Veriler Gecersizdir");
        }

    }
    private void kullanici_giris_yapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanici_giris_yapActionPerformed
        kullanici_giris_mesaj.setText("");
        String email = this.kullanici_adi.getText();
        String sifre = new String(this.sifre.getPassword());
        boolean girdimi = islemler.kullaniciGirisYap(email, sifre);
        if (girdimi == true) {
            int id = islemler.kullaniciID(email, sifre);
            KullaniciArayuz arayuz = new KullaniciArayuz(id);
            this.setVisible(false);
            this.setFocusable(false);

            arayuz.setVisible(true);
            arayuz.setFocusable(true);

        } else {
            kullanici_giris_mesaj.setText("giris başarısız tekrar deneyin");
        }
    }//GEN-LAST:event_kullanici_giris_yapActionPerformed

    private void kayit_normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayit_normalActionPerformed
        String kayit_turu = "nor";
        kayitBilgiAl(kayit_turu);
    }//GEN-LAST:event_kayit_normalActionPerformed

    private void kayit_preActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayit_preActionPerformed
        String kayit_turu = "pre";
        kayitBilgiAl(kayit_turu);
    }//GEN-LAST:event_kayit_preActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admin_giris_paneli;
    private javax.swing.JButton admin_giris_yap;
    private javax.swing.JLabel admin_giris_yap_mesaj;
    private javax.swing.JButton admin_girisi;
    private javax.swing.JPanel giris_paneli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField kayit_ad;
    private javax.swing.JTextField kayit_email;
    private javax.swing.JLabel kayit_mesaj;
    private javax.swing.JButton kayit_normal;
    private javax.swing.JButton kayit_pre;
    private javax.swing.JTextField kayit_sifre;
    private javax.swing.JTextField kayit_ulke;
    private javax.swing.JTextField kullanici_adi;
    private javax.swing.JLabel kullanici_giris_mesaj;
    private javax.swing.JPanel kullanici_giris_paneli;
    private javax.swing.JButton kullanici_giris_yap;
    private javax.swing.JButton kullanıcı_girisi;
    private javax.swing.JPanel panel_kayit;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField sifre;
    private javax.swing.JTextField username;
    private javax.swing.JButton uye_ol;
    // End of variables declaration//GEN-END:variables
}
